export const mockCustomers = [
    {
        firstName: "Jon",
        lastName: "Smith",
        email: "jon.smith@example.com",
        phone: "(555) 010-1001",
        address: "101 Elm St, Springfield, IL 62701",
        customerId: 1001,
    },
    {
        firstName: "Jon",
        lastName: "Smyth",
        email: "jon.smyth@example.com",
        phone: "(555) 010-1002",
        address: "102 Elm St, Springfield, IL 62701",
        customerId: 1002,
    },
    {
        firstName: "John",
        lastName: "Smith",
        email: "john.smith@example.com",
        phone: "(555) 010-1003",
        address: "103 Elm St, Springfield, IL 62701",
        customerId: 1003,
    },
    {
        firstName: "Jon",
        lastName: "Smithers",
        email: "jon.smithers@example.com",
        phone: "(555) 010-1004",
        address: "104 Elm St, Springfield, IL 62701",
        customerId: 1004,
    },
    {
        firstName: "Jonathan",
        lastName: "Smith",
        email: "jonathan.smith@example.com",
        phone: "(555) 010-1005",
        address: "105 Elm St, Springfield, IL 62701",
        customerId: 1005,
    },
    {
        firstName: "Jon",
        lastName: "Smitt",
        email: "jon.smitt@example.com",
        phone: "(555) 010-1006",
        address: "106 Elm St, Springfield, IL 62701",
        customerId: 1006,
    },
    {
        firstName: "Jon",
        lastName: "S. Smith",
        email: "jon.s.smith@example.com",
        phone: "(555) 010-1007",
        address: "107 Elm St, Springfield, IL 62701",
        customerId: 1007,
    },
    {
        firstName: "Jonn",
        lastName: "Smith",
        email: "jonn.smith@example.com",
        phone: "(555) 010-1008",
        address: "108 Elm St, Springfield, IL 62701",
        customerId: 1008,
    },
    {
        firstName: "Jon",
        lastName: "Smith-Jones",
        email: "jon.smithjones@example.com",
        phone: "(555) 010-1009",
        address: "109 Elm St, Springfield, IL 62701",
        customerId: 1009,
    },
    {
        firstName: "J.",
        lastName: "Smith",
        email: "j.smith@example.com",
        phone: "(555) 010-1010",
        address: "110 Elm St, Springfield, IL 62701",
        customerId: 1010,
    },
];