import type { Metadata } from "next";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import {Grid, Container} from "@mui/material";
import {TopBar} from "@/components/navigation/topBar";
import { ClientTheme} from "@/theme/theme";
import {CssBaseline} from "@mui/material";
import React from "react";
import {store} from './store';
import {ReduxProvider} from "@/components/reduxProvider";
import {IconSideBar} from "@/components/navigation/iconSideBar";
import {SideDrawer} from "@/components/navigation/sideDrawer";
import { FadeAnimation } from "@/components/animations/fadeAnimation";


/**
 * Next.js route-level metadata for the application. Adjust as needed per route.
 */
export const metadata: Metadata = {
  title: "Dashboard Demo",
  description: "Generated by create next app",
};


/**
 * Root layout component that wraps its children with a consistent structure,
 * including theming, state management, and global styles.
 *
 * @param {Object} props - The properties object.
 * @param {React.ReactNode} props.children - The child components to be rendered within the layout.
 * @return {JSX.Element} The rendered layout structure including Redux, theming, and global configuration.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {


    return (
    <html lang="en">

      <body >

      <AppRouterCacheProvider>

          <ReduxProvider store={store}>


              <ClientTheme >
                  <CssBaseline/>
<FadeAnimation>
      
                  <Grid container spacing={1}>
      <Grid size={{sm: 12}}>
      <TopBar/>
      </Grid>
      <Grid size={{sm:1}}>
      <IconSideBar/>
          {/*<SideDrawer/>*/}
      </Grid>



        <Grid size={{sm:11}}>
            <Container maxWidth="xl">
        {children}
            </Container>
        </Grid>
        </Grid>
        </FadeAnimation>
    </ClientTheme>

          </ReduxProvider>

      </AppRouterCacheProvider>
      </body>

    </html>
  );
}
